"use client";
import { useEffect, useState } from "react";

type Property = { id: string; name: string; slug: string; city?: string | null; locality?: string | null; propertyType: string; latitude: number; longitude: number; coverImage?: string | null };
export default function PropertyResults() {
  const [properties,setProperties]=useState<Property[]>([]); const [q,setQ]=useState(""); const [type,setType]=useState("ALL"); const [loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true); const params=new URLSearchParams(); if(q) params.set("q",q); if(type!=="ALL") params.set("type",type); fetch(`/api/property-platform/properties?${params}`).then(r=>r.ok?r.json():{properties:[]}).then(d=>setProperties(d.properties??[])).catch(()=>setProperties([])).finally(()=>setLoading(false));},[q,type]);
  return <div><div style={{display:"grid",gap:12,marginBottom:22}}><input aria-label="Search properties" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search property, city or locality" style={{width:"100%",padding:"14px 16px",border:"1px solid #d6d6d2",borderRadius:8,fontSize:14}}/><select aria-label="Property type" value={type} onChange={e=>setType(e.target.value)} style={{padding:"13px 16px",border:"1px solid #d6d6d2",borderRadius:8,fontSize:14}}><option value="ALL">All property types</option><option value="RESIDENTIAL">Residential</option><option value="COMMERCIAL">Commercial</option><option value="MIXED_USE">Mixed use</option><option value="PLOT">Plot</option><option value="REDEVELOPMENT">Redevelopment</option></select></div><p style={{fontSize:12,letterSpacing:".08em",textTransform:"uppercase",color:"#777"}}>{loading?"Loading properties…":`${properties.length} properties`}</p><div style={{display:"grid",gap:12}}>{properties.map(p=><a key={p.id} href={`/properties/${p.slug}`} style={{display:"block",padding:16,border:"1px solid #e4e4df",borderRadius:10,textDecoration:"none",color:"inherit",background:"#fff"}}><div style={{fontSize:11,letterSpacing:".08em",color:"#9a7b3f",textTransform:"uppercase"}}>{p.propertyType.replaceAll("_"," ")}</div><h2 style={{margin:"6px 0",fontSize:20}}>{p.name}</h2><p style={{margin:0,color:"#6d6d69",fontSize:13}}>{p.locality ? `${p.locality}, ` : ""}{p.city ?? ""}</p></a>)}</div>{!loading&&!properties.length&&<div style={{padding:"40px 8px",color:"#777",fontSize:14}}>No published properties match your search yet.</div>}</div>;
}
